server:
  port: 1080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306?my_sys/serverTimezone=Asia/Shanghai
    username: root
    password: txy813

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: top.steventan.logindemo.domain
